### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cangkui6** [davidwushi1145/YNU-xk_spider_Refactoring#1]
ERROR - 登录失败: Timeout value connect was <object object at 0x00000210E544AD60>, but it must be an int, float or None.

**Comment by cangkui6** [comment]
已解决:selenium要求urllibs版本为1.26，requests要求urllibs版本<1.25,>=1.21.

升级requests版本为最新版，就可以兼容。

**Comment by cangkui6** [comment]
issue:验证码图像加载失败，达到最大刷新次数

**Comment by davidwushi1145** [comment]
请把完整的具体报错贴上来

**Comment by davidwushi1145** [comment]
> issue:验证码图像加载失败，达到最大刷新次数

请考虑是否正确运行了api.py的验证码校验模块
