### ISSUE TITLE
体育课报错

### ISSUE THREAD

**Issue by hsfuhf** [davidwushi1145/YNU-xk_spider_Refactoring#4]
1，如果是['网球（四）', '吴梦']，且体育课分男女，那么同性别满了异性还有空位的情况下，会一直提示有空位并尝试去选课。现在还没开放反馈是不在选课时间范围，看看明天会是什么情况
2，如果打全名，例如
 'peCourses': [
         ['23-网球（四）', '吴梦']，就会报错：2024-12-26 00:13:16,844 - ERROR - 选课过程中出错: list index out of range

**Comment by davidwushi1145** [comment]
实际表单中课程名与页面上显示并不一致，可以自行考虑抓取更多信息加入表单中实现选择特定性别的课，具体可自行修改getcourse.py

**Comment by hsfuhf** [comment]
感谢感谢
