### ISSUE TITLE
等待按钮加载时报错

### ISSUE THREAD

**Issue by cangkui6** [davidwushi1145/YNU-xk_spider_Refactoring#5]
Waiting for element //button[@class="bh-btn bh-btn bh-btn-primary bh-pull-right"] to be present
Failed to locate element //button[@class="bh-btn bh-btn bh-btn-primary bh-pull-right"] within 15 seconds: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6D9FE6C85+28821]
	(No symbol) [0x00007FF6D9F53810]
	(No symbol) [0x00007FF6D9DF578A]
	(No symbol) [0x00007FF6D9E491BE]
	(No symbol) [0x00007FF6D9E494AC]
	(No symbol) [0x00007FF6D9E92647]
	(No symbol) [0x00007FF6D9E6F33F]
	(No symbol) [0x00007FF6D9E8F412]
	(No symbol) [0x00007FF6D9E6F0A3]
	(No symbol) [0x00007FF6D9E3A778]
	(No symbol) [0x00007FF6D9E3B8E1]
	GetHandleVerifier [0x00007FF6DA31FC7D+3408013]
	GetHandleVerifier [0x00007FF6DA3373EF+3504127]
	GetHandleVerifier [0x00007FF6DA32B5CD+3455453]
	GetHandleVerifier [0x00007FF6DA0ABD8B+835995]
	(No symbol) [0x00007FF6D9F5EB2F]
	(No symbol) [0x00007FF6D9F5A7E4]
	(No symbol) [0x00007FF6D9F5A97D]
	(No symbol) [0x00007FF6D9F4A169]
	BaseThreadInitThunk [0x00007FFDB980257D+29]
	RtlUserThreadStart [0x00007FFDBAD8AF28+40]

2024-12-26 10:49:20,048 - ERROR - 登录失败: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6D9FE6C85+28821]
	(No symbol) [0x00007FF6D9F53810]
	(No symbol) [0x00007FF6D9DF578A]
	(No symbol) [0x00007FF6D9E491BE]
	(No symbol) [0x00007FF6D9E494AC]
	(No symbol) [0x00007FF6D9E92647]
	(No symbol) [0x00007FF6D9E6F33F]
	(No symbol) [0x00007FF6D9E8F412]
	(No symbol) [0x00007FF6D9E6F0A3]
	(No symbol) [0x00007FF6D9E3A778]
	(No symbol) [0x00007FF6D9E3B8E1]
	GetHandleVerifier [0x00007FF6DA31FC7D+3408013]
	GetHandleVerifier [0x00007FF6DA3373EF+3504127]
	GetHandleVerifier [0x00007FF6DA32B5CD+3455453]
	GetHandleVerifier [0x00007FF6DA0ABD8B+835995]
	(No symbol) [0x00007FF6D9F5EB2F]
	(No symbol) [0x00007FF6D9F5A7E4]
	(No symbol) [0x00007FF6D9F5A97D]
	(No symbol) [0x00007FF6D9F4A169]
	BaseThreadInitThunk [0x00007FFDB980257D+29]
	RtlUserThreadStart [0x00007FFDBAD8AF28+40]

**Comment by davidwushi1145** [comment]
![image](https://github.com/user-attachments/assets/45d3be88-1f22-4b5a-bb14-dd78652d01d5)
本地测试没有问题，请考虑自身网络问题
